name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Authenticate with Google Cloud
        run: echo '${{ secrets.GCP_SA_KEY }}' > "$HOME/gcp-key.json"

      - name: Deploy to Google App Engine
        run: |
          gcloud auth activate-service-account --key-file="$HOME/gcp-key.json"
          cd Backend/milestone-1/
          mvn clean package appengine:deploy
