name: Update Google Cloud App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Activate service account credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json

      - name: Deploy to Google Cloud
        run: |
          cd milestone-1
          mvn clean package appengine:deploy
