name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install dependencies and build
        run: |
          mvnw_path=$(find . -name mvnw)
          echo "mvnw found at: $mvnw_path"
          cd "$(dirname "$mvnw_path")"  # Change directory to where mvnw is located
          ./mvnw install -DskipTests=true
          ls -l target # Debug statement to list the contents of the target directory

      - name: Deploy to Google Cloud App Engine
        uses: GoogleCloudPlatform/github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          version: ${{ github.sha }}
          runtime: java11
          deploy_dir: ./milestone-1/target
