jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file="$HOME/gcp-key.json"

      - name: List contents of project directory
        run: ls -la "$project_dir"

      - name: Build and deploy with Maven
        run: mvn clean package appengine:deploy
