name: Update Google Cloud App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Activate service account credentials
        run: gcloud auth activate-service-account --key-file='${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Google Cloud
        run: |
          cd milestone-1
          mvn clean package appengine:deploy
